// Generated by https://quicktype.io

import { OptionSetItems } from "./option-set-items";

export interface OptionSet {
  id:             string;
  name:           string;
  displayNameAr:  string;
  displayNameEN:  string;
  optionSetItems: OptionSetItems[];
}
